course-id: capp30122-win-21
course-name: Computer Science with Applications II
quarter: Winter
year: 2021
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: capp30122-win-21
gitlab-upstream-repo: capp30122-win-21
chisubmit-init: true
chisubmit-course: capp30122-win-21
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH
