course-id: cmsc12300-spr-19
course-name: Computer Science with Applications III
quarter: Spring
year: 2019
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cmsc12300-spr-19
gitlab-upstream-repo: cmsc12300-spr-19
chisubmit-init: true
chisubmit-course: cmsc12300-spr-19
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH
