course-id: cmsc12200-win-21
course-name: Computer Science with Applications II
quarter: Winter
year: 2021
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cmsc12200-win-21
gitlab-upstream-repo: cmsc12200-win-21
chisubmit-init: true
chisubmit-course: cmsc12200-win-21
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH