course-id: cmsc12200-win-22
course-name: Computer Science with Applications II
quarter: Winter
year: 2022
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cmsc12200-win-22
gitlab-upstream-repo: cmsc12200-win-22
chisubmit-init: true
chisubmit-course: cmsc12200-win-22
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH