course-id: cmsc12200-win-20
course-name: Computer Science with Applications II
quarter: Winter
year: 2020
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cmsc12200-win-20
gitlab-upstream-repo: cmsc12200-win-20
chisubmit-init: true
chisubmit-course: cmsc12200-win-20
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH